/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yd8sJFPmZTe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import Image from "next/image";

export function SigninForm() {
  return (
    (<div
      className="flex min-h-screen items-center justify-center bg-gray-100 dark:bg-gray-950">
      <div
        className="mx-auto w-full max-w-md space-y-8 rounded-lg bg-white p-8 shadow-lg dark:bg-gray-900">
        <div className="space-y-2 text-center">
          <div className="flex items-center gap-2 justify-center">
            {/* <BadgeIndianRupeeIcon className="h-12 w-12 mr-2" />
             */}
            <Image src='/logo.png' height={100} width={100} />
            {/* <h1 className="text-3xl font-bold">Agent Login</h1> */}
          </div>
          <p className="text-gray-500 dark:text-gray-400">Sign in to your account</p>
        </div>
        <form className="space-y-6">
          <div>
            <Label htmlFor="username">Username</Label>
            <Input className="mt-1" id="username" placeholder="Enter your username" required />
          </div>
          <div>
            <Label htmlFor="password">Password</Label>
            <Input
              className="mt-1"
              id="password"
              placeholder="Enter your password"
              required
              type="password" />
          </div>
          <Button className="w-full" type="submit">
            Sign In
          </Button>
        </form>
        <div className="flex items-center justify-between">
          <Link
            className="text-sm text-gray-500 hover:underline dark:text-gray-400"
            href="#">
            Forgot password?
          </Link>
          <Link
            className="text-sm text-gray-500 hover:underline dark:text-gray-400"
            href="#">
            Create an account
          </Link>
        </div>
      </div>
    </div>)
  );
}

function BadgeIndianRupeeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
      <path d="M8 8h8" />
      <path d="M8 12h8" />
      <path d="m13 17-5-1h1a4 4 0 0 0 0-8" />
    </svg>)
  );
}
